USE `db_diintec`;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM `tbl_project_image`;
DELETE FROM `tbl_project`;
ALTER TABLE `tbl_project` AUTO_INCREMENT = 1;

INSERT INTO `tbl_project` (`title`, `slug`, `description`, `long_description`, `category`, `image`, `client_name`, `city`, `project_url`, `is_featured`, `sort_order`, `state`) VALUES
('Hullka Coffee',
 'hullka-coffee',
 'Sistema integral interno para procesos de café: socios, acopio, producción y facturación electrónica completa.',
 'Plataforma a medida que digitaliza toda la operación de Hullka Coffee en Jaén: gestión de socios productores con reportes LPA y certificados, geolocalización de parcelas, control de acopio, sistema de tickets, procesos de producción del café, facturación electrónica SUNAT, libros contables y kardex completo. Una sola fuente de verdad para finanzas, operación y campo.',
 'Sistema web a medida',
 'assets/img/logo-hullka.png',
 'Hullka Coffee',
 'Jaén',
 'https://hullkacoffee.pe/',
 1, 1, 'active'),

('Aprocam',
 'aprocam',
 'Sistema integral para procesos de cacao con app móvil offline para trabajo en campo.',
 'Plataforma robusta para la cooperativa Aprocam: gestión de socios productores, reportes LPA, certificados, geolocalización de parcelas con polígonos, acopio, caja, sistema de tickets, procesos de producción del cacao, facturación electrónica completa, libros contables y kardex. Incluye aplicativo móvil offline-first para que los técnicos registren datos en campo sin internet y sincronicen al volver a la cobertura.',
 'Sistema web + App móvil',
 'assets/img/logo-aprak.png',
 'Aprocam',
 'Amazonas',
 '',
 1, 2, 'active'),

('Aprak Perú',
 'aprak',
 'Landing page corporativa multilenguaje (español / inglés) para exportadora de naranja.',
 'Diseño y desarrollo de la web corporativa de Aprak Perú, exportadora de productos derivados de naranja en Chanchamayo. Sitio bilingüe (ES/EN), historia de la empresa, línea de productos y formulario comercial. Optimizado para SEO internacional y velocidad de carga.',
 'Landing corporativa',
 'assets/img/logo-aprak.png',
 'Aprak Perú',
 'Junín — Chanchamayo',
 'https://aprakperu.com/',
 1, 3, 'active'),

('Nuam Centro Educativo',
 'nuam',
 'Plataforma académica con exámenes virtuales, módulo de padres y landing corporativa.',
 'Sistema integral para Nuam Centro Educativo: gestión académica de alumnos, exámenes virtuales con corrección automática, módulo de padres para seguir el rendimiento de sus hijos en tiempo real, capacitaciones online y landing page corporativa para mostrar la propuesta educativa de la institución.',
 'Plataforma educativa',
 'assets/img/logo-nuam.png',
 'Nuam',
 'Lima',
 '',
 1, 4, 'active'),

('Meddi — Citas médicas',
 'meddi',
 'Intranet y extranet médica con integración HubSpot, pasarela de pago y panel doctor.',
 'Ecosistema digital para Meddi: extranet pública para que pacientes agenden citas médicas online, intranet para administradores con métricas y gestión integral, panel para doctores donde actualizan reportes de pacientes, integración con HubSpot como CRM y métodos de pago integrados (tarjeta, yape, plin). Perfiles diferenciados con permisos granulares.',
 'Intranet / Extranet',
 'assets/img/logo-hullka.png',
 'Meddi',
 'Lima',
 'https://citasenlinea.meddi.pe/login',
 1, 5, 'active'),

('Ayllu Eventos',
 'ayllu-eventos',
 'Landing corporativa + presupuestador online interactivo y dashboard de gestión.',
 'Sitio web para Ayllu Eventos con un presupuestador online donde los clientes arman su propio presupuesto para su evento (matrimonios, corporativos, sociales). Dashboard administrativo para presupuestos presenciales, gestión completa del contenido del sitio, sistema de roles, categorías de servicios y catálogo de productos.',
 'Landing + Presupuestador',
 'assets/img/logo-hullka.png',
 'Ayllu Eventos',
 'Lima',
 'https://ayllueventos.com/',
 1, 6, 'active'),

('Astur Santa Fe',
 'astur-santa-fe',
 'Hotel, restaurante y turismo: reservas, facturación electrónica SUNAT y gestión integral.',
 'Plataforma 360 para Astur Santa Fe: landing informativa del hotel, restaurante y agencia de turismo. Administrador general con listado de reservas de hotel, mesas del restaurante y guías planificadas de turismo. Módulo de facturación electrónica SUNAT completo para las ventas del restaurante. Reportes y gestión centralizada.',
 'Hotel & Restaurante',
 'assets/img/logo-astur.png',
 'Astur Santa Fe',
 'Lima',
 'https://astursantafe.com/',
 1, 7, 'active'),

('Lamour.pe',
 'lamour',
 'SEO y posicionamiento web: 2 años en primeros puestos de Google.',
 'Estrategia SEO sostenida para Lamour.pe durante 2 años: investigación de keywords competitivas, creación y optimización de contenido para el blog, link building, mejora de Core Web Vitals y autoridad de dominio. Resultado: primeros puestos en Google para diversas palabras clave del nicho.',
 'SEO y Marketing',
 'assets/img/logo-hullka.png',
 'Lamour',
 'Lima',
 'https://lamour.pe/',
 0, 8, 'active'),

('SanValentin.com.pe',
 'san-valentin',
 'Posicionamiento SEO con contenido temático y blogs optimizados para conversión.',
 'Trabajo SEO para SanValentin.com.pe: estrategia anual de contenido temático, creación de blogs optimizados, posicionamiento en primeros puestos de Google para palabras clave de alta intención. Crecimiento sostenido de tráfico orgánico cualificado.',
 'SEO y Marketing',
 'assets/img/logo-hullka.png',
 'SanValentin.com.pe',
 'Lima',
 'https://sanvalentin.com.pe/',
 0, 9, 'active'),

('Canastas Corporativas',
 'canastas-corporativas',
 'SEO y posicionamiento web: primeros puestos en palabras clave de regalos corporativos.',
 'Posicionamiento orgánico para CanastasCorporativas.pe: estrategia SEO con foco en intención comercial B2B, blogs corporativos y optimización on-page. Primeros puestos en Google para palabras clave del nicho de regalos y canastas corporativas.',
 'SEO y Marketing',
 'assets/img/logo-hullka.png',
 'Canastas Corporativas',
 'Lima',
 'https://canastascorporativas.pe/',
 0, 10, 'active'),

('TransporteSafe México',
 'transportesafe',
 'Plataforma de reservas de viajes con pasarela, gestión de rutas y app para conductores.',
 'Plataforma completa para TransporteSafe en México: landing pública para reservar viajes por zonas de recojo, integración con pasarela de pago, sistema administrativo completo con gestión de rutas, tickets y reservas, y módulo dedicado para conductores con asignación de viajes y reportes. Pensado para escalar a múltiples ciudades.',
 'Plataforma de reservas',
 'assets/img/logo-hullka.png',
 'TransporteSafe',
 'México',
 'https://transportesafe.com/',
 1, 11, 'active');

SET FOREIGN_KEY_CHECKS = 1;
